### ISSUE TITLE
Some sort of infinite loop is getting created!

### ISSUE THREAD

**Issue by HammadNasir** [rupinderjeet/NotificationActionButtonExample#1]
hey, it sort of worked but for testing purpose I wrote the code which only takes me to MainActivity without checking any condition on clicking "Accept". It worked, but the only problem is that some sort of infinite loop is created. Like when I'm pressing back after getting sent to MainActivity from the notification, it is reopening again and again and the Toast are appearing again and again!!! :/

**Comment by rupinderjeet** [comment]
As our discussion on [stackoverflow](http://chat.stackoverflow.com/rooms/130429), this particular issue has been solved.
